# Generated by Django 4.1.1 on 2023-01-31 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_brand', models.CharField(max_length=200, null=True)),
                ('item_name', models.CharField(max_length=200, null=True)),
                ('item_desc', models.CharField(max_length=200, null=True)),
                ('item_color', models.CharField(max_length=200, null=True)),
                ('item_price', models.IntegerField()),
            ],
        ),
    ]
