# Generated by Django 4.1.1 on 2023-01-31 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://www.willow-car-sales.co.uk/wp-content/uploads/2019/11/placeholder-image-1.jpg', max_length=500),
        ),
    ]
